name:                topocity
version:             0.1.0.0
github:              "polaretto/topocity"
license:             UNLICENSE
author:              "Ennio Visconti"
maintainer:          "ennio.visconti@gmail.com"
copyright:           "2018 Ennio Visconti"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/polaretto/topocity#readme>

dependencies:
- BiGUL
- hxt
- base >= 4.7 && < 5

library:
  source-dirs:
  - src
  - src/data
  - src/libs

executables:
  topocity-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - topocity

tests:
  topocity-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - topocity
