name:                topocity
version:             0.1.0.0
github:              "polaretto/topocity"
license:             OtherLicense
author:              "Ennio Visconti"
maintainer:          "ennio.visconti@gmail.com"
copyright:           "2018 Ennio Visconti"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/polaretto/topocity#readme>

dependencies:
- BiGUL
- hxt
- hxt-expat
- base #>= 4.7 && < 4.10
- graphviz
- text
- citygml4hs
- fgl
- process
- directory
- time
- binary
- data-ordlist

library:
  source-dirs:
  - src

executables:
  topocity-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - topocity
    - data-default
    - mtl

tests:
  topocity-test:
    main:                Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - topocity
    - tasty
    - tasty-hunit
    - tasty-smallcheck
    - tasty-quickcheck
    - tasty-hspec
